name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
      - name: deploy
        run: |
          exclusion_patterns=$(cat exclusion-patterns.txt | tr '\n' '|')
          zip -r deploy.zip $(git ls-files | grep -v -E "$exclusion_patterns" | tr '\n' ' ')
          aws lambda update-function-code --function-name=lamda-test-1 --zip-file=fileb://deploy.zip